name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull na Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/kotlin:v1

      - name: Remove no Container
        run: docker rm -f kcontainer || true

      - name: Rodando container
        run: docker run --name kcontainer -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/kotlin:v1